/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface OwnableInterface extends utils.Interface {
  functions: {};

  events: {
    "OwnershipAssigned(address[3])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipAssigned"): EventFragment;
}

export type OwnershipAssignedEvent = TypedEvent<
  [[string, string, string]],
  { owners: [string, string, string] }
>;

export type OwnershipAssignedEventFilter =
  TypedEventFilter<OwnershipAssignedEvent>;

export interface Ownable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OwnableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "OwnershipAssigned(address[3])"(
      owners?: [string, string, string] | null
    ): OwnershipAssignedEventFilter;
    OwnershipAssigned(
      owners?: [string, string, string] | null
    ): OwnershipAssignedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
